USE [ProjetoKeepWalking]
GO

/****** Object:  Table [dbo].[Opcionais]    Script Date: 17/12/2015 14:54:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Opcionais](
	[idOpcional] [int] IDENTITY(1,1) NOT NULL,
	[nomeOpcional] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Opcionais] PRIMARY KEY CLUSTERED 
(
	[idOpcional] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

